// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SocketIO","status":true,"description":"v2.0.4 - Socket.IO (for Alpha NET plugin)","parameters":{}},
{"name":"Alpha_NET_build","status":true,"description":"v0.7.900 Network system (Beta)","parameters":{"Alpha NET":"","GameMode":"Cooperative","ActorsForPlayers":"1, 2, 3, 4","NetworkEvents":"--- --- --- --- ---","ServerStarted":"1","OnConnect":"0","OnDisconect":"0","OnOtherCon":"2","OnOtherDisc":"3","OnPvPEnd":"0","NetworkUI":"--- --- --- --- ---","NameplatesMode":"Others","_supporters":"Thanks to these guys!","Donald Derrick":"","Ilya Chkoliar":"https://elushisgaming.club/","Kevin Sjöberg":"","Sarcastic Sloth":"https://sarcasticsloth42.wixsite.com/avillainstale","Plerai":""}}
];
